### ISSUE TITLE
AutoAction - the flow with custom agent 

### ISSUE THREAD

**Issue by phodal** [unit-mesh/auto-dev#100]
aka AutoFlow

**Comment by phodal** [comment]
Docs: https://ide.unitmesh.cc/devins/orchestration.html

Next Task: SmallAgent

like:  update xxx in `method` (/symbol:xxx.method)

tdd with Auto

**Comment by Cha-Ching13** [comment]
I appreciate and support you! I'm not much help at coding but thank you for going hard

**Comment by ymli0215** [comment]
@phodal 
請問，Flow的功能還沒有實作  對嗎？？？

**Comment by phodal** [comment]
嗯，还不确定最后的形态

**Comment by ymli0215** [comment]
想問一下Floe的用途

例如測試流程 : 取得針對整檔或是部分內容->產生junit test code -> write to file -> run test code
這些動作應該會透過 /file、/write、/run 連續去跑
這時候就是Flow希望做到的事情，對嗎？？

**Comment by phodal** [comment]
对，当时设计的想法是这样的。

1. 由 #79 生成对应的  tasking。类似于 AI  生成的任务规划
2. 由 #100  这里执行对应的  action

所以，基本上这个  issue  算是完成了，只是没有测试过连贯性。

**Comment by ymli0215** [comment]
但是你說 這個issue算是完成，但是沒有測試過連貫性，那是不是可以跟我說要怎樣測試，我試試看呢
agent 回傳
```
`` ` devin
[flow]:xxx.devin  
`` `
```
想要去呼叫我實體存在的xxx.devin，但看起來沒動靜

**Comment by phodal** [comment]
那可能是  bug 了，哈哈哈，因为调起来成本很高

**Comment by ymli0215** [comment]
求實現... XD

**Comment by phodal** [comment]
@ymli0215 我提交了一个简单的实现上去，你先试试。剩下的只能以后再做了

**Comment by ymli0215** [comment]
回報一下

透過對話視窗  flow簡單測試成功

用 單獨.devin檔案去執行flow就沒有效果，我這邊找找看問題是啥，看看有沒有可能我可以知道怎樣改...XD

**Comment by ymli0215** [comment]
針對DevInsProcessProcessor 加上你的做法就可以了

**Comment by phodal** [comment]
现在应该是不支持回传的。原始版本的 DevIns Flow 设计是这样的：

假设当前是  `action_1.devin`

```
[flow]:flow/action_2.devin

xxx action 1
```

默认的设计应该是：

1. 当你执行完现在的  flow，即：`action_1.devin`
2. 在结束后会检查是 comments  里的内容，即 `[flow]:flow/action_2.devin`
3. 执行 `action_2.devin` 中的内容

理论上，如果 `action_2.devin` 不执行 agent  的话，可能是个  bug ？？


PS：預期 agent 只呼叫一次是在 chat panel  中的行为，如果是单独的 .devin  文件，可能是会执行的 —— 待确定。
