### ISSUE TITLE
Can I Change timeout of the LLM?

### ISSUE THREAD

**Issue by jason-webcomm** [unit-mesh/auto-dev#106]
Can I Change timeout of the LLM? The default timeout is 60. But my server is slow to generate code review & document. Is it possible to change the timeout?

**Comment by phodal** [comment]
the Default timeout is 600s:

https://github.com/unit-mesh/auto-dev/blob/91acc81947ca73ab0cb5c87cd8d0acc3383a5138/src/main/kotlin/cc/unitmesh/devti/llms/LLMProvider.kt#L9-L29

current you cannot config for this, maybe can try to PR.
