### ISSUE TITLE
AutoDev AI AutoAction-> Code complete功能时好时坏

### ISSUE THREAD

**Issue by liuq29** [unit-mesh/auto-dev#107]
INFO - #cc.unitmesh.devti.llms.custom.CustomLLMProvider - Requesting form: {"messages":[{"role":"user","content":"你好\n"},{"role":"user","content":"code complete for given code, just return rest part of code. \npackage cn.com.pip.oap.pos.common.controller;\n\nimport io.swagger.v3.oas.annotations.tags.Tag;\nimport io.swagger.v3.oas.annotations.Operation;\nimport org.springframework.beans.factory.annotation.Value;\nimport org.springframework.web.bind.annotation.RequestMapping;\nimport org.springframework.web.bind.annotation.RequestMethod;\nimport org.springframework.web.bind.annotation.RestController;\n\n/**\n * Application name:oneAPP平台</br>\n * Application description: </br>\n * Company:AIA</br>\n * Date:2020/11/04 17:43\n *\n * @author suiguojun\n * @version 1.0\n * @since 1.0\n */\n@Tag(name=\"服务版本\")\n@RestController\n@RequestMapping(\"/\")\npublic class VersionController {\n\n    @Value(\"${oap.version}\")\n    private String version;\n\n    @Operation(summary=\"获取版本\")\n\t@RequestMapping(value = \"/getVersion\", method = RequestMethod.GET)\n    public String getVersion(){\n        return version;\n    }\n\n    public void bubbleSort(){\n        \n\nreturn rest code:"},{"role":"user","content":"你好\n"},{"role":"user","content":"\n\n```Java\npublic void bubbleSort(){\n\n    }\n```"}],"model":"deepseek-coder-6.7b","stream":true} okhttp3.RequestBody$Companion$toRequestBody$2@1689599c

INFO - #cc.unitmesh.devti.gui.chat.ChatCodingPanel - **onCompletion null**
INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - **Saving global entities to files**
INFO - #c.i.i.p.m.MarketplaceRequests - **Can not get JetBrains plugins' IDs from Marketplace: Connect timed out**
INFO - #c.i.u.MemTester - **not supported: Windows is not supported**
INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl **- Saving global entities to files**
INFO - #c.i.i.p.m.MarketplaceRequests - Can not get supported extensions from Marketplace: Connect timed out
INFO - #c.i.i.p.m.MarketplaceRequests - Can not get JetBrains plugins' IDs from Marketplace: Connect timed out
INFO - #c.i.i.p.m.MarketplaceRequests - Can not get supported extensions from Marketplace: Connect timed out
WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
INFO - #c.i.i.p.m.MarketplaceRequests - Error reading Marketplace file: java.net.SocketTimeoutException: Connect timed out 

idea 我在我的Java方法里右键使用AutoDev AI AutoAction-> Code complete后没有反应，查看idea 日志如上，后来我把idea关闭重启又没问题了，时好时坏，当使用Code complete没有反应后，再打开chat聊天窗口聊天也会没有反应。请问大佬为啥日志里显示要去连接插件市场呢？我是在公司内网环境使用的，coder模型也是公司内网环境部署的

**Comment by phodal** [comment]
1. Code complete 如果出错的话，似乎 IDEA  会判定有问题。但是，理论上不会影响聊天窗口，有可能服务器卡住？
2. 不确定为什么  JetBrains  会去请求他们的 Marketplace。

**Comment by liuq29** [comment]
公司服务器部署的coder模型响应很快的，查看模型日志，服务器响应完成插件还没有出来结果，谢谢大佬的回答，我再研究研究
