### ISSUE TITLE
插件支持WebSocket方式连接LLM吗？

### ISSUE THREAD

**Issue by liuq29** [unit-mesh/auto-dev#108]
ws://10.199.35.10:8080/chat

大佬，插件支持WebSocket方式连接模型吗？

**Comment by phodal** [comment]
不支持，需要自己来  PR：

参考：https://github.com/unit-mesh/auto-dev/blob/master/src/main/kotlin/cc/unitmesh/devti/llms/xianghuo/XingHuoProvider.kt

https://github.com/unit-mesh/auto-dev/blob/df2bb82e4af08afd1fe0db9a431cfbf1e923cf2f/src/main/kotlin/cc/unitmesh/devti/llms/xianghuo/XingHuoProvider.kt#L67-L80
