### ISSUE TITLE
请问这个项目和微软的Autodev是什么关系？Could you please explain the relationship between this project and Microsoft’s Autodev?

### ISSUE THREAD

**Issue by firehuman100** [unit-mesh/auto-dev#111]

**Comment by phodal** [comment]
这个项目和微软的 AutoDev，就是雷锋与雷锋塔的关系。我们是在 2023 年 4 月份开源的，目标是一个在 IDE 环境内，构建自动化编码的环境。

详细见我们在去年  4 月份的  Demo  视频：[AutoCRUD - 自动化的 CRUD 代码编写：ChatGPT + Intellij IDEA 结合会变成怎样？](https://www.bilibili.com/video/BV1QV4y1Z7w5/)

和微软的 AutoDev 只是在理念上和功能上有诸多的相似性，诸如于自动编码等等。通过 Agent 和 指令对代码库进行自动化操作，我们的 AutoDev 是通过构建 DevIns  语言来提供这种能力，详细见：[#101](https://github.com/unit-mesh/auto-dev/issues/101)。

欢迎参与到这个项目，AutoDev 内建的任务规划功能正在开发中: #79 ，有兴趣欢迎入坑。

**Comment by phodal** [comment]
8 months ago demos: https://www.youtube.com/watch?v=6Oghfm8blyY

**Comment by firehuman100** [comment]
> 这个项目和微软的 AutoDev，就是雷锋与雷锋塔的关系。我们是在 2023 年 4 月份开源的，目标是一个在 IDE 环境内，构建自动化编码的环境。
> 
> 详细见我们在去年 4 月份的 Demo 视频：[AutoCRUD - 自动化的 CRUD 代码编写：ChatGPT + Intellij IDEA 结合会变成怎样？](https://www.bilibili.com/video/BV1QV4y1Z7w5/)
> 
> 和微软的 AutoDev 只是在理念上和功能上有诸多的相似性，诸如于自动编码等等。通过 Agent 和 指令对代码库进行自动化操作，我们的 AutoDev 是通过构建 DevIns 语言来提供这种能力，详细见：[#101](https://github.com/unit-mesh/auto-dev/issues/101)。
> 
> 欢迎参与到这个项目，AutoDev 内建的任务规划功能正在开发中: #79 ，有兴趣欢迎入坑。
> 
> This project and Microsoft's AutoDev are akin to the relationship between Lei Feng and LeiFeng Tower. We open-sourced it in April 2023 with the aim of creating an environment for automated coding within an IDE.
> 
> For more details, refer to our demo video from April last year: [AutoCRUD - Automated CRUD Code Generation: How Does it Work with ChatGPT + Intellij IDEA?](https://www.bilibili.com/video/BV1QV4y1Z7w5/)
> 
> While there are numerous similarities in concept and functionality with Microsoft's AutoDev, such as automated coding, our AutoDev operates through the development of the DevIns language to provide this capability, as detailed in #101.
> 
> Feel free to join this project; the built-in task planning feature in AutoDev is currently under development: #79. If you're interested, we welcome you to get involved.

谢谢解答，从目前来看，微软的Autodev项目只有论文公开了，这个项目已经跑在了微软的前面。
Thank you for your answer. As of now, Microsoft’s Autodev project only has a paper published. Your project has already surpassed Microsoft.

**Comment by Outliers1106** [comment]
Speaking of which, thanks to Microsoft for letting me find out such an excellent open-source project. lol

**Comment by LeoLiuYan** [comment]
Keep an eye on this project !

**Comment by jaredjared** [comment]
pycharm插件怎么搜不到？

**Comment by phodal** [comment]
@jaredjared 好像是 IDEA marketplace 标记成 不维护，可以访问安装 https://plugins.jetbrains.com/plugin/21520-autodev/

**Comment by jaredjared** [comment]
谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "unit-mesh/auto-dev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [unit-mesh/auto-dev] 请问这个项目和微软的Autodev是什么关系？Could you please explain the relationship between this project and Microsoft’s Autodev? (Issue #111)





 
@jaredjared 好像是 IDEA marketplace 标记成 不维护，可以访问安装 https://plugins.jetbrains.com/plugin/21520-autodev/

**Comment by phodal** [comment]
应该是兼容性的问题
