### ISSUE TITLE
你好，构建的时候有2个文件不存在

### ISSUE THREAD

**Issue by Klein73** [unit-mesh/auto-dev#112]
![image](https://github.com/unit-mesh/auto-dev/assets/143162299/ac249ecc-efcd-4679-a059-861bfa405059)

你好，这个文件里的这两个飘红的文件，在代码库里确实是没有的，不过run用例能正常run起来，请问这个问题需要关注吗？

**Comment by phodal** [comment]
IDEA  中的 Gradle 同步问题，大概率是因为你电脑卡住导致的，可以再 sync  一下。

生成  lexer  和  parser 的时候，会生成一个 gen  目录，

<img width="468" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/ce3935d9-e828-46b8-ad66-5c3126332636">

详细原理见：

https://github.com/unit-mesh/auto-dev/blob/2796660dcd8dae37db3e9cdf974f3fa5df6ef21f/build.gradle.kts#L601-L620
