### ISSUE TITLE
华为DevEco Studio鸿蒙开发支持安装AutoDev插件吗？

### ISSUE THREAD

**Issue by liuq29** [unit-mesh/auto-dev#121]
Hi 大佬，我看文档上写的插件支持DevEco Studio,但是我去插件市场却没有看到插件支持DevEco Studio呢，这是什么情况？

![image](https://github.com/unit-mesh/auto-dev/assets/20152198/c643dba2-ecf9-4648-b905-817aa9e69672)

![image](https://github.com/unit-mesh/auto-dev/assets/20152198/d275b97e-271d-4f6f-b31c-ad13fd53e1c2)

**Comment by phodal** [comment]
JetBrains 官方的插件市场只支持官方  IDE。基于  JB  平台的三方 IDE 需要自己下载插件，DevEcoStudio 是基于 222～232  之间，需要下载 - 222  结束的版本。

<img width="1043" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/d35d8697-aa31-4392-bbeb-db23d401ca61">
