### ISSUE TITLE
当选择“中文”时，希望所有提示词能够使用中文

### ISSUE THREAD

**Issue by ouwx** [unit-mesh/auto-dev#125]
目前虽然语言选择“中文”，但是每次问题都是英文回答，因为你的prompt用的是英文，可以添加多语言支持。
当原因选择“中文”后，所有prompt切换为中文，这样llm返回就会是英文了
支持您，加油

**Comment by phodal** [comment]
@jialiu-github 你最想作的功能

**Comment by jialiu-github** [comment]
这个正在开发中

**Comment by jialiu-github** [comment]
PR #131
