### ISSUE TITLE
如何生成dto、service、controller、sql代码？整个流程是怎么样的？  下面这个界面功能和一般的工具一样啊

### ISSUE THREAD

**Issue by shenxunan** [unit-mesh/auto-dev#13]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/fce6c1b7-278e-466c-a770-fa6abe971ae6)

**Comment by shenxunan** [comment]
开发者要怎么和这个工具交互，怎么使用这个工具来完成具体的开发，好像完全没有讲明白

**Comment by shenxunan** [comment]
开发者要怎么和这个工具交互，怎么使用这个工具来完成具体的业务开发，好像完全没有讲明白

**Comment by phodal** [comment]
参考文档：https://github.com/unit-mesh/auto-dev#autocrud-mode

**Comment by shenxunan** [comment]
自定义提示在哪里配置？   add // devti://story/github/1 comments in your code.

**Comment by shenxunan** [comment]
1、自定义提示在插件上面哪里配置？  
2、下面这个生成的是基于你自己定义的博客的用户故事，如何修改成自己的用户故事? 
add // devti://story/github/1 comments in your code.

**Comment by shenxunan** [comment]
> 1、自定义提示在插件上面哪里配置？
> 2、下面这个生成的是基于你自己定义的博客的用户故事，如何修改成自己的用户故事?
> add // devti://story/github/1 comments in your code.

**Comment by phodal** [comment]
随便找个地方，写下 ：`// devti://story/github/1`

**Comment by phodal** [comment]
未来（代码库已d有，未发布）可以直接选中需求，然后生成：
<img width="711" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/472311/faa211f8-be6b-4c52-ab7d-ba0e8171ed39">

**Comment by shenxunan** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/c828e175-333f-4fd3-9247-b5076f4c077e)

**Comment by shenxunan** [comment]
token数量不够，这个代码生成后能自动分到每个文件吗？

**Comment by phodal** [comment]
哈哈，再提个新 issue 吧，上下文没控制好
