### ISSUE TITLE
idea intention 菜单提供重命名函数，变量功能

### ISSUE THREAD

**Issue by zjh7890** [unit-mesh/auto-dev#132]
有时候懒得想函数名...

**Comment by zjh7890** [comment]
老哥有交流群吗，我也想加入 hhh

**Comment by phodal** [comment]
没有了，懒得建，之前有一个辅助研发的：phodal02

**Comment by zjh7890** [comment]
> 想起来了，你这有点费 token

哈哈，充值就完事😂

**Comment by phodal** [comment]
第一个版本先这样：

<img width="609" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/5251ec7a-cee3-445c-9ece-a624fd733179">

等 build 完应该就可以体验了：https://github.com/unit-mesh/auto-dev/actions/runs/8524783767

你先测试测试，我来加个 toggle

**Comment by phodal** [comment]
详细 prompt 见：

https://github.com/unit-mesh/auto-dev/blob/44008dc0a538d441f1a4e55cbac6d483b27d029c/src/main/kotlin/cc/unitmesh/devti/practise/RenameLookupManagerListener.kt#L37-L46

**Comment by zjh7890** [comment]
你这迭代效率也太给力了...

**Comment by phodal** [comment]
不过，有 bug ，等我关了  isue，再测试吧

**Comment by zjh7890** [comment]
> 不过，有 bug ，等我关了 isue，再测试吧

ok

**Comment by phodal** [comment]
可以体验了，https://plugins.jetbrains.com/plugin/21520-autodev/versions/snapshot

需要从配置中打开功能，

<img width="1148" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/09cc4f76-4fe9-4cdb-b1e0-82fdb4f4d943">

**Comment by zjh7890** [comment]
> 可以体验了，https://plugins.jetbrains.com/plugin/21520-autodev/versions/snapshot
> 
> 需要从配置中打开功能，
> 
> <img alt="图片" width="1148" src="https://private-user-images.githubusercontent.com/472311/319064073-09cc4f76-4fe9-4cdb-b1e0-82fdb4f4d943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjc1ODgsIm5iZiI6MTcxMjEyNzI4OCwicGF0aCI6Ii80NzIzMTEvMzE5MDY0MDczLTA5Y2M0Zjc2LTRmZTktNGNkYi1iMWUwLTgyZmRiNGY0ZDk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwNjU0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2MyYjhmMmUwYTlmYzIwYmI0MDdlMjI3ZWQzZTI3YWFjZjc5NjFkMDkwMzJkODQ5NDcxY2JjMDYwYTc4YzMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qPnAN3AE1xWv2knSFYuoV-1LWxSTlXoacSBSJq2L4qE">

ok
