### ISSUE TITLE
如何配置本地部署的LLM， deepseek-coder-7b?

### ISSUE THREAD

**Issue by biostone** [unit-mesh/auto-dev#147]
**Describe the bug**

本地用vllm部署了deepseek-coder-7b, OpenAI compatible 模式。用NextChat，Continue.dev 都测试过，LLM server是部署成功的。

但是，在Auto-Dev中不可以用，具体请看附件截图。

Unit Mesh 这个理念非常正点，非常希望能够用起来。谢谢！

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Main Version [e.g. 22]
 - IDEA Version [e.g. Intellij IDEA 2024.3]

**Additional context**
<img width="1005" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/17900807/c3417713-46a1-471d-aa43-b9a6f3257afc">

**Comment by phodal** [comment]
上面显示 404，这不是路径不对吗。。

**Comment by biostone** [comment]
在NextChat里，是这样配置：
<img width="597" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/17900807/96d110c0-cae2-4860-9748-fef12e21d8b4">

在Continue.dev 里是这样配置：
<img width="396" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/17900807/d12064a0-81e2-4c83-9511-30ab6addfe5d">

在AutoDev里，这样配置，结果就404错。试过：http://192.168.20.20:8082， http://192.168.20.20:8082/v1, http://192.168.20.20:8082/v1/chat, http://192.168.20.20:8082/v1/chat/completions, 都是报同样的错：

<img width="1022" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/17900807/8e95220c-f6fb-4dde-bfa1-b656c9bc50b9">

非常 感觉您花时间帮我排错！

**Comment by biostone** [comment]
现在好了
<img width="1034" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/17900807/ebce2056-9bc0-4043-a99f-a94ffb44153d">
