### ISSUE TITLE
设置成中文后,回复依然是英文

### ISSUE THREAD

**Issue by 32ns** [unit-mesh/auto-dev#151]
设置成中文后,回复依然是英文;
![image](https://github.com/unit-mesh/auto-dev/assets/1725120/bc71f113-99c9-4593-b969-8e2b387878ec)

如果选项可以删除就好了,有些功能用不上,上下选还麻烦
![image](https://github.com/unit-mesh/auto-dev/assets/1725120/47098ea3-bd88-4e0c-8339-df630c940838)

修复功能好像不可用,我选择的错误和助手发送的不一致
![image](https://github.com/unit-mesh/auto-dev/assets/1725120/44faae6d-f986-49cb-86bc-e1744981fa2a)

**Comment by phodal** [comment]
1. 系统中还有一些高级上下文，比如当前的框架信息等等，使用的是英语。所以，要么你的问题最好是中文的，要么禁止这个高级上下文/

<img width="459" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/40ae2d6c-2a67-4aea-99fb-9a24a3b3cf43">

2. 这个配置目前不支持删除，不确定哪些是用处不大的。

3. 修复功能，没有在  Goland  测试过，可能有  bug 。

**Comment by 32ns** [comment]
> 1. 系统中还有一些高级上下文，比如当前的框架信息等等，使用的是英语。所以，要么你的问题最好是中文的，要么禁止这个高级上下文/
> 
> <img alt="图片" width="459" src="https://private-user-images.githubusercontent.com/472311/323428921-40ae2d6c-2a67-4aea-99fb-9a24a3b3cf43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTEyOTcsIm5iZiI6MTcxMzQxMDk5NywicGF0aCI6Ii80NzIzMTEvMzIzNDI4OTIxLTQwYWUyZDZjLTJhNjctNGFlYS05OWZiLTlhMjRhM2IzY2Y0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMzI5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2ZjN2M1NjQ4YzNlMmNiYWVhNDg3MGM2OGVhNjA3ODRlNWZkZWVhN2E3Nzc4NzJkMWQwMDUyMjg4ZDFjZGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TmPec4pu1E-tkiAGLMi6FBmXy88qGVOpE85DJurbOBw">
> 2. 这个配置目前不支持删除，不确定哪些是用处不大的。
> 3. 修复功能，没有在  Goland  测试过，可能有  bug 。

我禁用掉高级上下文同样还是输出的英语,看来goland中还是有点问题,不过可以通过自定义提示来解决,问题不大

**Comment by phodal** [comment]
@32ns 确认了一下，应该是  Go  语言没有实现高级 `ContextPrompter`，所以调用了 `DefaultContextPrompter`，这里面没有实现对应的语言翻译。另外，对应的第  3  个问题，也是由于没有调用到上下文导致的。

已经提交了修复，详细见：https://github.com/unit-mesh/auto-dev/commit/ea2bac296602f496848e933ed6cb11f39a1b626a

等这个  build  完就可以下载到对应的修复：https://github.com/unit-mesh/auto-dev/actions/runs/8732947810

**Comment by 32ns** [comment]
> @32ns 确认了一下，应该是 Go 语言没有实现高级 `ContextPrompter`，所以调用了 `DefaultContextPrompter`，这里面没有实现对应的语言翻译。另外，对应的第 3 个问题，也是由于没有调用到上下文导致的。
> 
> 已经提交了修复，详细见：[ea2bac2](https://github.com/unit-mesh/auto-dev/commit/ea2bac296602f496848e933ed6cb11f39a1b626a)
> 
> 等这个 build 完就可以下载到对应的修复：https://github.com/unit-mesh/auto-dev/actions/runs/8732947810

这修复速度真是绝了,一会没注意就修好了 😂
