### ISSUE TITLE
Support Maven build

### ISSUE THREAD

**Issue by ymli0215** [unit-mesh/auto-dev#164]
從JavaAutoTestService看到有放一個   todo: add maven ??
測試起來應該也還沒有支援Maven吧??

請問我想要動手增加，除了UI部分
應該是針對哪幾隻程式去做調整比較好呢??
不然我就是一個一個慢慢查有gradle的蹤影，同時增加maven處理
這樣怕有遺漏，也怕沒有效率

**Comment by phodal** [comment]
现在相关的任务应该是：

- 获取构建任务信息，以用于生成  dockerfile 、 jenkinsfile 等信息。详细见：JavaBuildSystemProvider
- 利用 Gradle  来执行生成的测试。见：JavaAutoTestService
- 生成上下文所需要的依赖信息，诸如  Spring boot  测试等。见：SpringContextProvider

**Comment by ymli0215** [comment]
抱歉，因為真沒有開發過，想問個基本問題
就是我要import新的程式，是怎樣做的

例如 JavaAutoTestService.kt有 import GradleRunConfiguration，他要怎樣做才能import成功??
我目前想要增加支援Maven，所以想import org.jetbrains.idea.maven.execution.MavenRunConfiguration
結果不知道怎樣去設定相關環境.. @@

**Comment by phodal** [comment]
IDEA 的插件，如果依赖于特定的其它插件，比如  maven，需要手动添加依赖。

这里应该有类似于 `org.jetbrains.plugins.maven` 的依赖：

https://github.com/unit-mesh/auto-dev/blob/3e890afd1d1fc8e1853481bf89c0d6c6e45c13bd/build.gradle.kts#L94-L100

随后再  Gradle Sync  一下试试。

**Comment by phodal** [comment]
我刚大概看了一下  Maven 的  plugin 名字应该是：`org.jetbrains.idea.maven`，

至于如何创建的逻辑，我还没研究过，可以参考：

https://github.com/JetBrains/intellij-community/blob/9b5e8782f3e31be25eb2a38bbb31edab58cf36c4/plugins/maven/src/main/java/org/jetbrains/idea/maven/execution/MavenRunAnythingProvider.kt

**Comment by c913168497** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/23418458/7bc98574-b0d3-4da2-bc71-01466c468d98)
我想你说的是这个
![image](https://github.com/unit-mesh/auto-dev/assets/23418458/3a41166f-7b60-4139-9715-94102eafa9a4)
你可以把命令改为其它的

**Comment by phodal** [comment]
@c913168497 你看你都写好了，不来个  PR  吗，哈哈哈

**Comment by c913168497** [comment]
还没想好完整的功能设计啊 哈哈， 我目前都是脚本功能形式

**Comment by phodal** [comment]
哈哈，边写边想
