### ISSUE TITLE
pycharm多个版本安装报错

### ISSUE THREAD

**Issue by TingsongYu** [unit-mesh/auto-dev#167]
pycharm中安装报错如下：

1 of 1
Exception in plugin AutoDev (1.8.2-RC-233). Disable plugin...
This plugin is not a production of JetBrains. Please report the problem to the plugin vendor.
---
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
	at cc.unitmesh.devti.agent.CustomAgentExecutor.<init>(CustomAgentExecutor.kt:22)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:41)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:39)
  	... 148 more
---
请问是哪一步不正确，导致pycharm中无法正确使用该插件？

环境：
win11 
pycharm版本： 专业版, 2023.3.3
auto-dev版本：1.8.2-RC-233

操作步骤：
1. 下载intellij-autodev-1.8.2-RC-233.zip
2. 解压
3. 在pycharm中，Install plugin from disk ...
4. 选择intellij-autodev\lib\intellij-autodev-1.8.2-RC-233.jar
5. 重启pycharm

请问是否正确？期待回答，感谢

**Comment by TingsongYu** [comment]
已解决
```markdown

在PyCharm中手动安装插件通常指的是安装非官方或者尚未通过PyCharm插件市场发布的插件。如果你已经获取了一系列的JAR包，并且这些JAR包是一个完整的插件，你可以按照以下步骤进行手动安装：

关闭PyCharm：在安装插件之前，请确保PyCharm已经关闭，以避免安装过程中的冲突。

找到PyCharm的插件目录：

对于Windows系统，插件目录通常位于C:\Users\你的用户名\AppData\Roaming\JetBrains\PyCharm版本号\plugins。
对于macOS系统，插件目录通常位于~/Library/Application Support/JetBrains/PyCharm版本号/plugins。
对于Linux系统，插件目录通常位于~/.config/JetBrains/PyCharm版本号/plugins。
创建插件目录：在插件目录中创建一个新的文件夹，该文件夹的名称应与插件的ID或名称相对应。

复制JAR包：将所有的JAR包复制到你刚刚创建的插件目录中。

可能需要的其他文件：有些插件可能还需要一些配置文件，如plugin.xml等，如果这些文件存在，也应该将它们复制到插件目录中。

打开PyCharm：完成复制后，打开PyCharm。

检查插件是否安装成功：

转到“File” > “Settings”（Windows/Linux）或“PyCharm” > “Preferences”（macOS）。
在设置窗口中，选择“Plugins”。
在插件列表中查找你刚刚安装的插件，它应该出现在“Installed”标签页下。
应用更改：如果插件已正确显示，点击“Apply”按钮，然后重启PyCharm使插件生效。

**Comment by TingsongYu** [comment]
请问支持社区版pycharm吗?

**Comment by phodal** [comment]
安装方式不对，不需要解压，直接使用 zip 包
