### ISSUE TITLE
Auto-dev fine-tune dataset for ArkUI.

### ISSUE THREAD

**Issue by Zctoylm0927** [unit-mesh/auto-dev#169]
It is mentioned on the homepage that **ArkUI is supported.** 

How did you collect the data set when doing fine-tune on deepseek? Or is there a ready-made one that can be used?

**Comment by phodal** [comment]
we use RAG. https://github.com/unit-mesh/auto-dev/tree/master/exts/ext-harmonyos/src/main/kotlin/cc/unitmesh/harmonyos/actions/auto
