### ISSUE TITLE
能否修改ollama的链接？

### ISSUE THREAD

**Issue by wwjCMP** [unit-mesh/auto-dev#176]
使用非默认链接

**Comment by phodal** [comment]
请提供更详细的信息，无法理解你的问题是什么。

**Comment by wwjCMP** [comment]
> 请提供更详细的信息，无法理解你的问题是什么。

不实用 https://localhost:11434，使用自定义的链接

**Comment by phodal** [comment]
无法复现

**Comment by wwjCMP** [comment]
调用ollama需要填写他的url，默认是我上面的那个，但是有时候需要修改url。这个不需要复现 ，而是要实现

**Comment by phodal** [comment]
本地没有环境，欢迎来 PR

**Comment by hsl313** [comment]
现在最新的版本是不是不支持了？
