### ISSUE TITLE
chatglm无法使用

### ISSUE THREAD

**Issue by kenneth-bro** [unit-mesh/auto-dev#178]
**Describe the bug**
配置了 custom模型后为 chatglm的glm-4后，报错了，无法使用

**To Reproduce**
<img width="846" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/19256972/42efc657-0e53-4af1-9ad5-9bf8ad2d67e3">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1
 - Main Version:  1.8.0-241
 - IDEA Version: Intellij IDEA 2024.1.1

**Additional context**

**Comment by phodal** [comment]
duplicate to #90
