### ISSUE TITLE
Broken Links in Readme.md

### ISSUE THREAD

**Issue by scriptbotprime** [unit-mesh/auto-dev#179]
**Describe the bug**
At least two llinks in your Readme.md are broken:
* https://github.com/unit-mesh/auto-dev/blob/master/finetunes/deepseek
* https://ide.unitmesh.cc/quick-start

**Comment by phodal** [comment]
the second way should be works, maybe it's DNS issue.

**Comment by scriptbotprime** [comment]
It still doesn't work in Mozilla Firefox but Chrome is ok with https://ide.unitmesh.cc/quick-start

**Comment by phodal** [comment]
It's a DNS issue: https://www.whatsmydns.net/#A/ide.unitmesh.cc, I don't had a good DNS provider to support it.

<img width="1346" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/993e12af-b0ce-451c-abf1-118825743867">
