### ISSUE TITLE
chatglm2 怎么接入

### ISSUE THREAD

**Issue by rocymp** [unit-mesh/auto-dev#18]

**Comment by phodal** [comment]
参考：https://github.com/unit-mesh/auto-dev/blob/master/example/custom_llm_server/main.py 编写一个 API 作为代理

**Comment by rocymp** [comment]
这个已经接入进去了，主要是prompt有没有能在chatglm2上可以工作的。

**Comment by phodal** [comment]
解释什么的都还 Ok

**Comment by phodal** [comment]
而且还可以自定义
