### ISSUE TITLE
XingHuo LLM配置，显示2个星火API密钥

### ISSUE THREAD

**Issue by zhujunling-nj** [unit-mesh/auto-dev#186]
**Describe the bug**
XingHuo LLM配置，显示2个星火API密钥。

**To Reproduce**
1. Go to 'Plugins configure'
2. Click on 'LLM服务器'
3. Scroll down to 'XingHuo'

**Expected behavior**
一个是API Key，一个是API密钥

**Screenshots**
![image](https://github.com/unit-mesh/auto-dev/assets/26447863/a4f79bbc-2b8c-4c98-968c-6d0f3c930a05)

**Desktop (please complete the following information):**
 - OS: Windows
 - Main Version 1.8.3-RC-241
 - IDEA Version Intellij IDEA 2024.1

**Comment by phodal** [comment]
应该是中文翻译的问题 @jialiu-github

**Comment by zhujunling-nj** [comment]
> 应该是中文翻译的问题，欢迎来 PR
> 
> 每个是 API Key，第二个是 API Secret

配置后 Test LLM Connection，提示鉴权失败，返回401错误。
使用同样的API Key、Secret，通过Python SDK测试成功。

**Comment by zhujunling-nj** [comment]
> 应该是中文翻译的问题，欢迎来 PR
> 
> 每个是 API Key，第二个是 API Secret

多试几次后，测试通过。
多谢！
