### ISSUE TITLE
本地构建报错

### ISSUE THREAD

**Issue by SurzHp** [unit-mesh/auto-dev#187]
**Describe the bug**
作者您好，我想本地构建你的代码，执行 Run IDEA 报错 Cannot expand ZIP 'C:\Users\xxx\Desktop\auto-dev-master\plugin\build\idea-sandbox-241\plugins\autodev-jetbrains\lib\autodev-jetbrains-1.8.3-SNAPSHOT-241.jar'

.我看了下这个 autodev-jetbrains-1.8.3-SNAPSHOT-241.jar 是一个jar，且没啥实际内容，还请教下如何本地构建。

![image](https://github.com/unit-mesh/auto-dev/assets/8913148/efc99aaa-7102-4437-a880-746c901ece9e)
![image](https://github.com/unit-mesh/auto-dev/assets/8913148/041d1bc9-7691-4c44-b218-f556e4c95bf9)
![image](https://github.com/unit-mesh/auto-dev/assets/8913148/cfceea5b-ed1e-46ba-80b7-d7a362814535)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Main Version [1.8.3-RC]
 - IDEA Version [e.g. Intellij IDEA IC 2024.1]

**Comment by phodal** [comment]
信息太少，无法确定问题，建议参考：https://github.com/unit-mesh/auto-dev/blob/master/.github/workflows/build.yml

**Comment by SurzHp** [comment]
本地开发的话，是直接跑  Run IDEA/pycharm 就可以吗，还需要其他配置不

**Comment by phodal** [comment]
不需要，但是需要等  Gradle sync  完，可能大概要半天（～4 小时）

**Comment by SurzHp** [comment]
感谢 已搞定，我gradle版本太高了
