### ISSUE TITLE
You LLM server Key is empty

### ISSUE THREAD

**Issue by zhangchixx** [unit-mesh/auto-dev#188]
**Describe the bug**
我使用idea下的1.8.3-RC-241插件

**To Reproduce**
1. Go to 'settings->tools '
2. Click on 'AutoDev'
3. AI Engine设置 OpenAI
4. key和host设置完成后，点击测试按钮，提示我 You LLM server key is empty

**Expected behavior**
希望可以配通大模型接口

**Screenshots**
![llmerror](https://github.com/unit-mesh/auto-dev/assets/20252741/cfc8f9ec-19fb-4ea2-9945-20def6aca10b)

**Comment by zhangchixx** [comment]
使用custom模式也会报相同的错误
![llmerror2](https://github.com/unit-mesh/auto-dev/assets/20252741/e7594291-7a64-49af-8a75-5d5a947c912e)

**Comment by phodal** [comment]
需要先  apply  才能  test
