### ISSUE TITLE
为什么我的idea 安装了AutoDev 在AutoDev Chat下没有看到Create SQL 

### ISSUE THREAD

**Issue by huling2361** [unit-mesh/auto-dev#189]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Main Version [e.g. 22]
 - IDEA Version [e.g. Intellij IDEA 2024.3]

**Additional context**

**Comment by huling2361** [comment]
为什么我的idea 安装了AutoDev 在AutoDev Chat下没有看到Create SQL

**Comment by phodal** [comment]
你需要先连接数据库：https://ide.unitmesh.cc/workflow/auto-sql.html
