### ISSUE TITLE
请教：为何 AutoDevEditorListener 始终无法触发自动补全

### ISSUE THREAD

**Issue by fonlin** [unit-mesh/auto-dev#197]
无论如何输入，始终被这一行代码return了
`if (commandProcessor.currentCommandName != null) return`

**Comment by phodal** [comment]
有更详细的信息吗，我这补充是  OK  的

**Comment by fonlin** [comment]
我在这段逻辑打了几行日志，

**Comment by fonlin** [comment]
**IDE平台是241版本**
我将`AutoDevEditorListener`注册为了`editorFactoryListener`

然后我在这里打了几行日志，如下
![image](https://github.com/unit-mesh/auto-dev/assets/31064021/76911bf7-f387-4268-b238-1f3e6e93e94d)

启动后无论我怎么编辑代码，控制台仅输出如下日志，看上去是被`if (commandProcessor.currentCommandName != null) return`return掉了

**Comment by phodal** [comment]
理解了，可是这一块代码是没启用的，是要来  PR  吗

**Comment by fonlin** [comment]
好的，我也是在学习研究的阶段。你们对这块有新的规划吗？毕竟主流的插件都是实时的自动补全

**Comment by phodal** [comment]
暂时没有资源，有兴趣可以来贡献
