### ISSUE TITLE
实现快速的相似度搜索

### ISSUE THREAD

**Issue by c913168497** [unit-mesh/auto-dev#200]
1. 希望能实现一个功能，将文本数据向量化后存储在向量数据库中，以实现快速的相似度搜索，从而检索与输入查询相关的文本片段，再将检索到的文本输入，最终形成我需要的提示词

**Comment by phodal** [comment]
我们在 VSCode  版本实现了类似的功能，但是导致插件体积太大，暂时没有计划迁移到  IDEA  中。详细可以参考：https://github.com/unit-mesh/auto-dev-vscode

比较理想的形式应该是使用额外的  embedding  包和向量数据库

**Comment by c913168497** [comment]
有没有这方面embedding包和向量数据库推荐呢~

**Comment by phodal** [comment]
@c913168497 还有一个比较轻量级的实现，使用  TFIDF  算法。Copilot  主要用的就是他，和  embedding  之类的相比，还是相当靠谱的。

**Comment by c913168497** [comment]
牛 真的在实现了， 我试试

**Comment by c913168497** [comment]
看了一下代码 还在实现中～～～～ 加油～

**Comment by phodal** [comment]
只是接口上支持，功能还没实现
