### ISSUE TITLE
聊天支持发送图片

### ISSUE THREAD

**Issue by lecion** [unit-mesh/auto-dev#205]
# Feature Proposal: [聊天支持发送图片]

## Description

聊天支持发送图片

## Motivation

希望能够用到多模态 LLM，比如 GPT-4o，用于完成对于图片的理解，进一步能够实现 Design2Code 的相关功能

## Proposed Solution

目前想了两个交互：
1. 聊天窗口增加图片上传
2. 图片放到工程目录下，在 IDE 中选择图片右键能触发对应的 action 等

**Comment by phodal** [comment]
暂时没有可以测试的模型，欢迎来 PR 🤣🤣
