### ISSUE TITLE
星火 onMessage null

### ISSUE THREAD

**Issue by xxllp** [unit-mesh/auto-dev#207]
**Describe the bug**
配置的是星火的api，测试也可以的，但是执行autodev的各种操作assist 返回都是onMessage null
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="302" alt="微信图片_20240627092911" src="https://github.com/unit-mesh/auto-dev/assets/4278666/cb5a5dc9-5b6c-424c-b430-0cd90435a83f">

**Desktop (please complete the following information):**
pycharm 2024-1
windows
**Additional context**

**Comment by zhengxs2018** [comment]
星火几？我记得星火123版本的链接和key都不是不互通的

**Comment by xxllp** [comment]
星火2

**Comment by phodal** [comment]
能不换个别的模型，暂时没有精力支持这种奇怪的 API  格式。

**Comment by xxllp** [comment]
是我操作的问题，已经解决了。但是还有个问题就是为啥我下载最新的插件安装使用发现没有生成单元测试的功能，只是有生成api测试的功能

**Comment by phodal** [comment]
@xxllp 生成单元测试是使用  Intention，可以通过  alt + enter  或者选中对应的元素触发。
