### ISSUE TITLE
使用生成测试代码，未正确读取Web层接口对象结构

### ISSUE THREAD

**Issue by zhangzhiyi23** [unit-mesh/auto-dev#211]
我在IDEA中使用插件遇到了一些问题

## Environment
- AutoDev Version: 1.8.0-241
- Java Version: Java 8

## Steps to Reproduce
1.  在Web层选择一个含有复杂对象的接口
2. 代码位置右键，选择 AutoDev Chat -> 为此处编写测试（or 生成api测试数据）
3. 触发生成操作

## 代码示例
```java
    @PostMapping("setManagerUser")
    public Response<Boolean> setManagerUser(@RequestBody SetManagerUserRequestVo req) {
        return Response.OK(websiteManagerService.setManagerUser(req));
    }
```

我在架构图中有看到AST解析，预期生成相应的正确JSON数据结构作为测试输入，但是发送的对话、生成结果中似乎并没有相关内容

是不是配置问题，或是不支持该功能？

**Comment by phodal** [comment]
请从  release  中更新到最新版本，老版本可能有  bug
