### ISSUE TITLE
Is there a way to allow users to customize the parameters to control `Prompt` length?

### ISSUE THREAD

**Issue by LeoLiuYan** [unit-mesh/auto-dev#212]
# Feature Proposal:  Allow users to customize the length of `Prompt`.

## Description

As we know, the `Prompt` is very import for `AutoCompletion` and `Chat in repo`.  Is it necessary for users to customize the parameters to control the `Prompt`  length?

## Motivation

For example, to add `maxSuffixPercentage` and `maxPromptTokens` to control the maximum length of `prefix` field in `Prompt`.

**Comment by phodal** [comment]
Please use `Max token length` in AutoDev settings panel
