### ISSUE TITLE
idea 不知道怎么配置本地大模型，能出个教程吗？

### ISSUE THREAD

**Issue by Haifeng002** [unit-mesh/auto-dev#215]
idea 不知道怎么配置本地大模型，能出个教程吗？

**Comment by phodal** [comment]
参考：https://ide.unitmesh.cc/custom/llm-server

**Comment by Haifeng002** [comment]
没找到llama3的配置呢？

**Comment by zhengxs2018** [comment]
> 没找到llama3的配置呢？

你说的是部署本地模型？还是本地模型服务部署后，根据提供的 API 接入到插件？

**Comment by Haifeng002** [comment]
> > 没找到llama3的配置呢？
> 
> 你说的是部署本地模型？还是本地模型服务部署后，根据提供的 API 接入到插件？

idea 插件的配置截图教程可以来个吗？
