### ISSUE TITLE
为什么我在idea中的自动提示一直是python语法

### ISSUE THREAD

**Issue by zhzhlit** [unit-mesh/auto-dev#216]
如图，在设置里也没有找到设置语言的地方

![Xnip2024-07-19_16-47-45](https://github.com/user-attachments/assets/80abe4f5-786b-4b99-be01-06232001841f)

**Comment by phodal** [comment]
上下文太少，无法判断。

**Comment by zhzhlit** [comment]
> 上下文太少，无法判断。

操作系统：macOS 12.7.2
Idea版本：IntelliJ IDEA 2023.1.6
JDK版本：1.8
项目类型：Maven

请问还需要其他什么信息？

**Comment by phodal** [comment]
@zhzhlit 插件的版本，当前的项目文件？以及，你执行的操作是什么？使用哪个模型等等。

**Comment by zhzhlit** [comment]
> @zhzhlit 插件的版本，当前的项目文件？以及，你执行的操作是什么？使用哪个模型等等。

Java maven类型项目，对于任意一个Java文件，新建的也可以。使用的是星火模型，文本生成代码功能。

**Comment by zhzhlit** [comment]
> @zhzhlit 插件的版本，当前的项目文件？以及，你执行的操作是什么？使用哪个模型等等。

Java maven类型项目，对于任意一个Java文件，新建的也可以。使用的是星火模型，文本生成代码功能。

**Comment by zhzhlit** [comment]
![Xnip2024-07-24_07-59-58](https://github.com/user-attachments/assets/69a36b97-b345-4e9f-9783-54028891a760)
![Xnip2024-07-24_08-00-16](https://github.com/user-attachments/assets/0d056663-7639-45f3-8b74-4db33e2cc626)
![Xnip2024-07-24_08-00-36](https://github.com/user-attachments/assets/7baa0d78-123f-47dd-b482-4486a612d668)

**Comment by phodal** [comment]
用法不对，这里的  quick assistant  并不支持这么使用。

- 如果你要用补全的话，需要用  inlay  或者 右键。
- 使用  Prompt Override 将  quick asssistant  改为你想要的功能，详细见：https://ide.unitmesh.cc/customize/prompt-override.html
