### ISSUE TITLE
这里有个bug, 如果选取的内容过长， 这个使用这个 方法，会导致堆栈溢出

### ISSUE THREAD

**Issue by c913168497** [unit-mesh/auto-dev#217]
![111](https://github.com/user-attachments/assets/06239d7e-bb48-4d36-b26f-5bed05c3d3bd)
可以这样修复

**Comment by c913168497** [comment]
同时我增加了一个新功能，解决，我们生成sql的麻烦
![115](https://github.com/user-attachments/assets/7c838a6f-c6e2-42fb-be3d-3b7bee246834)
![114](https://github.com/user-attachments/assets/c751f2a0-a9cd-482d-bb0c-bafdab68e9d1)

**Comment by phodal** [comment]
直接来个  PR ？
