### ISSUE TITLE
`Test LLM Connection` returned an unexpected result

### ISSUE THREAD

**Issue by lkk214** [unit-mesh/auto-dev#219]
**Describe the bug**
When I don't click on **`Apply`** in `settings ->Tools ->AutoDev`, the test connection still uses the original configuration items.
Can it support using the latest configuration without clicking on **`Apply`**

**To Reproduce**
1. Go to `settings ->Tools ->AutoDev`
2. Click on `Test LLM Connection`, received an error message: **You LLM server Key is empty**
3. Add API key(or change the value of `AI Engine`), but don't click on **`Apply`**
4. Click on `Test LLM Connection`, received the same error message: **You LLM server Key is empty**

**Expected behavior**
The test connection can support using the latest configuration without clicking on **`Apply`**

**Additional context**
keep it and don't plan to make any changes?

**Comment by phodal** [comment]
We know it, but still had effort to change make it in data-binding.
