### ISSUE TITLE
将autodev 与 idea 的 LiveTemplate 结合， 做到选中部分常用代码， 右键点击，即可让AI 自动分析提取代码，生成Live Template 

### ISSUE THREAD

**Issue by c913168497** [unit-mesh/auto-dev#222]
![d8ce23d597990563327b08df26a4fa4](https://github.com/user-attachments/assets/4727aa02-1c63-4a18-837e-4f96c66a5d0d)

**Comment by phodal** [comment]
直接来  PR ？哈哈，还有上次那个

**Comment by c913168497** [comment]
哈哈哈哈， 我的代码库改动了好多，我编译你的好像编译不成功本地

**Comment by c913168497** [comment]
我得有空才能搞了，这个功能应该能解决常用api方法，但一下想不起来在哪里的问题

**Comment by phodal** [comment]
哈哈，可以核心代码先来  PR，有空我再修复一下
