### ISSUE TITLE
不支持新版本的idea 和android studio

### ISSUE THREAD

**Issue by Haifeng002** [unit-mesh/auto-dev#226]

**Comment by phodal** [comment]
请下载对应的版本，比如  241  应该下载  241。最新的  IDEA  应该从  release  中下载 最新版本

**Comment by Haifeng002** [comment]
在哪搜呢？ idea Marketplace 都搜不出来，下载 打包好的release版本，新版本idea 不支持

**Comment by phodal** [comment]
需要选择正确的版本：https://github.com/unit-mesh/auto-dev/releases
