### ISSUE TITLE
建议增加一个隐藏提示词的配置，因为如果配置的提示词内容比较多，每次提问，都会展示大段冗长的提示词，占用版面，又起不到任何作用，增加一个配置，可以随时隐藏或者展示

### ISSUE THREAD

**Issue by c913168497** [unit-mesh/auto-dev#227]
# Feature Proposal: [Feature Name]

## Description

A brief description of the feature you would like to see implemented.

## Motivation

Explain why this feature is important and/or how it will improve the project.

## Proposed Solution

Detail the solution you propose for this feature. This can include mockups, examples, or a detailed description of the implementation.

## Alternatives Considered

If you considered any alternatives, list them here and explain why they were not chosen.

**Comment by phodal** [comment]
有没有建议的设计 方式？

**Comment by c913168497** [comment]
你可以自定义配置中考虑增加一个选项，hidePrompt ， 如果hidePrompt =true, 那么display的提示词为：正在处理操作：title（也是配置中的参数）, 如果hidePrompt =false,为显示全部提示词，同时，默认hidePrompt=true, 这样就可以提升整个版面的有效使用率

**Comment by phodal** [comment]
直接来 PR？哈哈

**Comment by c913168497** [comment]
hahaha~
