### ISSUE TITLE
Support POE API

### ISSUE THREAD

**Issue by boostarcher** [unit-mesh/auto-dev#231]
POE supports many bots including claude 3.5 without charge. I saw that some guys developed bots with the POE API:
https://github.com/Timmy-web/Poe-Telegram-Chatbot?tab=readme-ov-file

https://github.com/poe-platform/fastapi_poe

Thus I was wondering if support for it can be added in this plugin, or if there is already support for it, how to set that up?

**Comment by boostarcher** [comment]
Here is the sample call in postman to poe api

Post https://api.poe.com/bot/Claude-3.5-Sonnet

Request Header:
host:api.poe.com 
accept-encoding:gzip, deflate 
connection:keep-alive
user-agent:python-httpx/0.27.0 
accept:text/event-stream 
cache-control:no-store
content-type:application/json
Authorization:Bearer <API Key, generated from https://poe.com/api_key>

Request body:
{
    "version": "1.0",
    "type": "query",
    "query": [{
            "role": "user",
            "sender_id": null,
            "content": "Hello world",
            "content_type": "text/markdown",
            "timestamp": 0,
            "message_id": "",
            "feedback": [],
            "attachments": []
        }
    ],
    "user_id": "",
    "conversation_id": "",
    "message_id": "",
    "metadata": "",
    "api_key": "<missing>",
    "access_key": "<missing>",
    "temperature": 0.7,
    "skip_system_prompt": false,
    "logit_bias": {},
    "stop_sequences": [],
    "language_code": "en",
    "bot_query_id": ""
}

Response:
{"text": " can I assist you today"}

**Comment by phodal** [comment]
I don't have Poe API, but I think custom req/res will support this. For more, see in : https://ide.unitmesh.cc/custom/llm-server
