### ISSUE TITLE
AutoDev的生成方法功能老是生成英文的

### ISSUE THREAD

**Issue by wuchubuzai2018** [unit-mesh/auto-dev#234]
如何解决IDEA插件中的autodev的生成文档注释功能老是生成英文的问题，我想让他生成中文的注释

**Comment by phodal** [comment]
切换成中文，或者使用 prompt override

**Comment by phodal** [comment]
试试这个：https://ide.unitmesh.cc/custom/living-documentation

**Comment by wuchubuzai2018** [comment]
> 试试这个：https://ide.unitmesh.cc/custom/living-documentation

试了一下，达不到【生成文档】那个自动Action的效果，这个必须提供example，不知道如何提供，我就想知道【生成文档】这个自动actions的提示词如何更改，没有找到，感觉像是代码中写死的

**Comment by phodal** [comment]
逻辑应该在这里：https://github.com/unit-mesh/auto-dev/blob/master/src/main/kotlin/cc/unitmesh/devti/intentions/action/task/LivingDocPromptBuilder.kt#L15

因为原来要区分类级、方法级和其它，所以是  hard code  的。
