### ISSUE TITLE
想要请教一下代码补全的功能

### ISSUE THREAD

**Issue by vincentwc** [unit-mesh/auto-dev#235]
我本地安装了AutoDev，连接本地的大模型，代码补全的功能是给我五点提示意见，这个可能涉及到prompt的设置，想请教一下，这个prompt的调参设置是在AutoDev这边还是在大模型那边，如果在AutoDev这边，在哪里设置prompt信息，谢谢

**Comment by phodal** [comment]
参考：https://ide.unitmesh.cc/customize/prompt-override.html

**Comment by vincentwc** [comment]
好的，谢谢

**Comment by vincentwc** [comment]
顺便请教一下，目前AutoDev是不是不支持代码实时补全，如果没有支持的话，有支持的计划吗？

**Comment by phodal** [comment]
现在是支持的，效果不好而已，参考：https://ide.unitmesh.cc/features/code-completion

**Comment by vincentwc** [comment]
好的，谢谢。
有没有那种我写代码的时候，自动弹出的代码补全，不需要用户去按键操作

**Comment by phodal** [comment]
没有，建议直接购买商用软件
