### ISSUE TITLE
Serializer for class 'CustomerRequest' is not found

### ISSUE THREAD

**Issue by ellie-tran** [unit-mesh/auto-dev#239]
**Describe the bug**
I encountered a problem while testing the LLM connection:
Serializer for class 'CustomerRequest' is not found. Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

**To Reproduce**
1. Go to Settings > Tools > AutoDev
2. Fill in the fields 'Custom Engine Server' and 'Custom Engine Token'
3. Click on 'Test LLM Connection'

**Screenshots**
![Screenshot from 2024-10-03 10-11-05](https://github.com/user-attachments/assets/b0a9071d-9ab3-479a-8ba5-74b5a6c5ac14)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Main Version: 22.04
 - IDEA Version: Intellij IDEA  2024.2.3

**Comment by phodal** [comment]
follow: https://ide.unitmesh.cc/custom/llm-server

make sure `Custom request format ` and `Custom response format` exists

**Comment by phodal** [comment]
Ops, it's a but in new version

**Comment by phodal** [comment]
release new version: https://github.com/unit-mesh/auto-dev/releases/tag/v1.8.12
