### ISSUE TITLE
最新版本的IDEA插件怎么把Git Log那个区域的代码评审选项去掉了

### ISSUE THREAD

**Issue by wuchubuzai2018** [unit-mesh/auto-dev#240]
原来旧版本的IDEA插件中的Git log区域有：生成发布说明和代码评审，更新为1.8.11、1.8.12版本后，代码评审的右键操作选项没有了，是去掉了吗，我非常喜欢这个功能，是BUG吗

**Comment by phodal** [comment]
我本地（2024.2.3）是有的，你看看是不是你的  IDEA  版本的问题

**Comment by wuchubuzai2018** [comment]
> 我本地（2024.2.3）是有的，你看看是不是你的 IDEA 版本的问题
没有，本地IDEA一直用的是2024.1.4，换了这个版本的电脑都不行，切换回1.8.9版本就有，用11和12版本就没有了。
![autodev-1](https://github.com/user-attachments/assets/1446fba3-a73f-4dbd-a3a8-0a2043d6ee2a)

**Comment by phodal** [comment]
应该是个 bug，可以从  GitHub Action  下载最新版本。
