### ISSUE TITLE
为什么有的时候IDEA里面的代码我修改后没提交执行预审查的时候提示【No Code To review】

### ISSUE THREAD

**Issue by wuchubuzai2018** [unit-mesh/auto-dev#241]
为什么有的时候IDEA里面的代码我修改后没提交执行预审查的时候提示【No Code To review】。
好像没提交的代码，只会对新增的文件进行评审，不是新增的文件，评审的的时候，就是提示：【No Code To review】

**Comment by phodal** [comment]
有可能是计算出来的  diff 有问题，详细入口 见：

https://github.com/unit-mesh/auto-dev/blob/8e4b28742f669ea776837d2ee5b6cfba9b4a3ef5/exts/ext-git/src/main/kotlin/cc/unitmesh/git/actions/vcs/CodeReviewAction.kt#L74-L80

**Comment by phodal** [comment]
需要你给出更详细的场景

**Comment by wuchubuzai2018** [comment]
> 需要你给出更详细的场景

找个项目，随便修改一个文件就行，修改的文件不可以。新增的文件没问题

**Comment by phodal** [comment]
IDEA 这个接口比较麻烦，要  add  才能，只获取变更好像没有接口。后续再看看有没有优化的方式
