### ISSUE TITLE
开启多个IDEA Windows窗口时，prompts团队的自定义提示词只取值了第一次打开的Windows了。

### ISSUE THREAD

**Issue by wuchubuzai2018** [unit-mesh/auto-dev#242]
**Describe the bug**
使用IDEA打开不同项目时，每个项目用一个独立的IDEA Windows窗口，每个项目不同的提示词，然后第二个IDEA Windows创建的提示未生效，始终读取的第一个项目Window里面的提示词，需要把第一个关闭

**Expected behavior**
期待2个IDEA项目的窗口都能同时生效

**Desktop (please complete the following information):**
 - OS: Windows
 - IDEA Version：IDEA 2024.1.4

**Comment by phodal** [comment]
暂时不能复现，确保一下目录是不是对的？

<img width="523" alt="图片" src="https://github.com/user-attachments/assets/d49904b1-42ed-4ad0-841e-0e9ca0cd1dd8">
