### ISSUE TITLE
 The results of the review are sometimes in English and sometimes in Chinese.  

### ISSUE THREAD

**Issue by yaunfang** [unit-mesh/auto-dev#243]
The language settings in the existing plugins are only for the operation interface. The results of the review are sometimes in English and sometimes in Chinese. I hope to modify them to be consistent with the set language.
A brief description of the feature you would like to see implemented.

**Comment by phodal** [comment]
1. try https://ide.unitmesh.cc/customize/prompt-override.html
2. try give PR to this project
