### ISSUE TITLE
设置语音为中文 但是生成文档注释内容是英文 这个有配置地方吗？

### ISSUE THREAD

**Issue by cxyxiaokui** [unit-mesh/auto-dev#245]
<img width="573" alt="image" src="https://github.com/user-attachments/assets/2dd351aa-c21d-48f8-84f0-518743747c4a">

<img width="558" alt="image" src="https://github.com/user-attachments/assets/d8d20bd9-eede-4902-8add-df62abc797c7">
<img width="735" alt="image" src="https://github.com/user-attachments/assets/4d72297b-f86b-422c-b1dd-9e346f3b6f9b">

尝试修改 prompt 也为生效

<img width="643" alt="image" src="https://github.com/user-attachments/assets/bf4b720f-1dcf-4f80-a001-8703544a9cc0">

**Comment by phodal** [comment]
这个是模型的问题，和工具本身关系不大的

**Comment by cxyxiaokui** [comment]
因为我看日志{"instruction":"Write documentation for given Java language class AiChatDTO.```Java\n@Data\npublic class AiChatDTO {\n\n    private Long id;\n\n    private String unionId;\n\n    private String serviceId;\n\n    private String content;\n\n    private Integer status;\n\n    private Date createTime;\n\n    private Date updateTime;\n}\n```\n\nStart your documentation with /** here, and ends with `*/`.\n\n- do not return example code, \n- do not use @author and @version tags","output":"```java\n/**\n * The `AiChatDTO` class is a Data Transfer Object (DTO) that encapsulates the data related to an AI chat interaction. \n * This class is typically used to transfer chat-related information between different layers of an application, \n * such as between the service layer and the presentation layer.\n * \n * The class includes fields that represent various attributes of a chat interaction, such as the unique identifier \n * for the chat, the union identifier, the service identifier, the content of the chat, the status of the chat, \n * and timestamps for when the chat was created and last updated.\n * \n * The class is annotated with `@Data`, which is a Lombok annotation that automatically generates common methods \n * such as getters, setters, `toString()`, `equals()`, and `hashCode()` for all fields.\n * \n * Fields:\n * - `id`: A unique identifier for the chat interaction.\n * - `unionId`: A unique identifier that may represent a union or group of related entities.\n * - `serviceId`: A unique identifier for the service associated with the chat interaction.\n * - `content`: The content of the chat message.\n * - `status`: The status of the chat interaction, represented as an integer. The meaning of the status value is \n *             application-specific and should be defined by the application's business logic.\n * - `createTime`: The timestamp indicating when the chat interaction was created.\n * - `updateTime`: The timestamp indicating when the chat interaction was last updated.\n * \n * This class is designed to be used in scenarios where chat-related data needs to be transferred between different \n * components of an application, such as between a service and a controller, or between a service and a database.\n */\n```"}  记录都是英文但是我配置的是中文。

**Comment by phodal** [comment]
重启过了？

**Comment by phodal** [comment]
想起来了，因为判断逻辑比较复杂，这里暂不支持中文。但是如果采用的是国内的模型就会生成中文，如 CodeGeex 等。

建议可以采用自定义文档生成，详细见：https://ide.unitmesh.cc/custom/living-documentation
