### ISSUE TITLE
Feature Request: LLM Restful format customizable

### ISSUE THREAD

**Issue by hotip** [unit-mesh/auto-dev#25]
Currently Restful format has 2 style, OpenAI and Azure , and Custom means Azure.

should be customizable for:

- set custom Header (for example: google's PaML2 api not need a Authorization header)
- append key to Url (for example: google's PaLM2 api append its key in url)
- customizable request body format

**Comment by phodal** [comment]
Haha, welcome to PR ~

**Comment by phodal** [comment]
@hotip 记得更新文档：https://github.com/unit-mesh/auto-dev/blob/master/docs/custom-llm-server.md
