### ISSUE TITLE
装在不同ide 菜单不一样，怎么配置？

### ISSUE THREAD

**Issue by EsMussSeinHui** [unit-mesh/auto-dev#28]
你好，我装在不同的ide，比如pycharm和idea,但是在idea里面有autoCrud，但是pycharm没有，请问是怎么配置使得在别的ide里面也支持autoCrud

**Comment by EsMussSeinHui** [comment]
我看文档看到了 这个comments in code..但是不是很理解
1. add `// devti://story/github/1` comments in your code.
2. configure GitHub repository for Run Configuration.
3. click `AutoDev` button in the comments' left.

**Comment by phodal** [comment]
那我注明一下，只在 Java 语言里支持。不是其它 IDE 的问题，而是其它语言不支持这种模式
