### ISSUE TITLE
custom engine server不生效，并没有请求自定义LLM接口

### ISSUE THREAD

**Issue by chisifang** [unit-mesh/auto-dev#31]
配置了custom engine server、custom engine token、response format，没有配置customize prompt。在LLM服务端监控autodev插件的调用情况，测试结果如下：

1. 部分功能不可用，LLM服务端没有收到请求。涉及功能：code complete、explain this、chat with this、chat with xxx（method），大多数功能都没有请求自定义模型接口
2. 只有autocrud with this 和 generate living doc 这2个功能调用了自定义模型接口，从模型服务端可以看到请求数据和返回。

对照源码：[CustomLLMProvider.kt](https://github.com/unit-mesh/auto-dev/blob/master/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt)。模型服务入参和返回都没有问题。

感觉插件中上述的几个功能并没有调用自定义模型地址，暂时还没有看到源码，先反馈一下，望回复，谢谢！

**Comment by phodal** [comment]
可能是因为 CustomLLMProvider 是通过依赖注入的方式实现的，所以在实例化之后，可能就会继续使用先前的配置。这个时候关闭一下 project，再打开就好了。

https://github.com/unit-mesh/auto-dev/blob/a0f16e9f79da579f6a2d624f570ce24b82b2906a/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt#L36C1-L36C32

**Comment by hotip** [comment]
我最新提交应该改了这个问题
