### ISSUE TITLE
new chat不生效

### ISSUE THREAD

**Issue by chisifang** [unit-mesh/auto-dev#35]
autodev配置了自定义custom engine server
case描述：autodev插件端点击"new chat"，同时关闭当前“code”对话框。这种情况下，按道理下次对话应该重置并开启新一轮对话，但实际不是。
重新使用autodev中随便一个功能，模型服务端依然会收到上一轮对话中全部message。
只有重新启动IDEA才会开启新一轮对话。

**Comment by phodal** [comment]
看来，和 #31 接近，需要优化一下这个模块了

**Comment by hotip** [comment]
也许让单例的 provider 保持无状态更好些

**Comment by phodal** [comment]
@hotip 哈哈，你那次可以改一改
