### ISSUE TITLE
关于添加 gitlab 的支持

### ISSUE THREAD

**Issue by GeekyWizKid** [unit-mesh/auto-dev#36]
如果谈论到私有化，那么大量的开发团队还使用了Gitlab 作为代码托管管理工具，是否应该添加支持，配置项目应该放在哪里合适？
我在老版本已经加过了不过更新之后没找到原先放github token 的地方

**Comment by phodal** [comment]
好像是改出 bug 了 @hotip

**Comment by hotip** [comment]
> 好像是改出 bug 了 @hotip
 
又漏显示一个配置项，我加一下
