### ISSUE TITLE
1.2.1 版本之后，模型返回的数据流输出不对

### ISSUE THREAD

**Issue by chisifang** [unit-mesh/auto-dev#48]
> @phodal 升级1.2.3不报错，但是模型返回的数据流没有正常输出。回滚到1.2.1版本之后一切正常。 模型服务一直没有改过，输入输出都是按照文档要求。 从现象看，就是1.2.1之后的版本对返回数据解析做了调整

建议新起个 issue

_Originally posted by @hotip in https://github.com/unit-mesh/auto-dev/issues/47#issuecomment-1754264565_

**Comment by chisifang** [comment]
输入：
{
    "messages": [
        {
            "message": "用java写一个快速排序",
            "role": "user"
        }
    ]
}
输出（第一条数据流）：
{
    "code": 200,
    "msg": "成功",
    "result": {
        "id": "",
        "status": 1,
        "message": "",
        "text": "Here"
    }
}
AutoDev插件配置的json path：$.result.text

**Comment by phodal** [comment]
代码上，看不到明显的变化，有明显的错误示例吗？

**Comment by chisifang** [comment]
intellij没有报错信息

**Comment by chisifang** [comment]
@phodal debug看了一下，CustomLLMProvider 104行，解析response出错
看改动是8月18日，删除了CustomLLMProvider中的parseChunkFromData方法，修改了response解析逻辑，只有配置了custom response format（json path）才会触发这个bug

**Comment by phodal** [comment]
来个 PR ？

**Comment by chisifang** [comment]
看之前的commit，8月18日那次commit是为了解决#25的问题。
恢复8月18日的代码依然报同一个错误java.lang.NoClassDefFoundError: Could not initialize class com.jayway.jsonpath.internal.JsonContext；感觉是版本依赖的问题
还在学习项目代码，PR这次先不提了

**Comment by chisifang** [comment]
but，debug结论如上，也可能我这边开发环境有问题， @phodal 可以测试一下

**Comment by phodal** [comment]
嗯，嗯，发现了，应该就是这里有问题

**Comment by phodal** [comment]
1.2.4 已发布：https://plugins.jetbrains.com/plugin/21520-autodev
