### ISSUE TITLE
请问gitlab token 需要配置怎么样的权限?

### ISSUE THREAD

**Issue by luozb** [unit-mesh/auto-dev#50]

**Comment by phodal** [comment]
参考一下配置：

<img width="507" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/55da3665-7554-48f0-b9b7-29c013906437">

对应的代码见：



https://github.com/unit-mesh/auto-dev/blob/094421f9c0d7b81fda54a8b2b4e7e4bb983d7974/src/main/kotlin/cc/unitmesh/devti/flow/kanban/impl/GitLabIssue.kt#L9-L15
