### ISSUE TITLE
213版本不兼容，代码无法build

### ISSUE THREAD

**Issue by chisifang** [unit-mesh/auto-dev#59]
以下文件报错：
1. AutoDevToolWindowFactory.kt:24:28 Unresolved reference: getInstance
2. CoUnitToolConfigurable.kt:36:21 Cannot find a parameter with this name: prop
3. TeamPromptsConfigurable.kt:26:21 Cannot find a parameter with this name: prop

**Comment by phodal** [comment]
213 之前评估过，需要修改的接口有点多，暂时没精力修复。

欢迎来 PR~。

**Comment by chisifang** [comment]
@phodal 221版本也不支持，但是看gradle-221.properties中配置是打算支持221（pluginSinceBuild = 221.*），实际只能支持222。
试着改为gradle-221.properties配置以兼容IDEA 221 - 221.6080版本，如下：
ideaVersion=IU-2022.1.4（之前版本：IU-2022.2.4）
pluginSinceBuild = 221（之前版本：221.*）
pluginUntilBuild = 232.*
修改AutoDevToolWindowFactory中代码兼容问题后，运行插件会报java版本问题：运行环境是java11，编译环境是17，插件无法启动，因为IDEA 222和221升级了gradle，从而需要java17？要适配221需要降低java版本？

**Comment by phodal** [comment]
哦，哦，那可能和 213 是同一个问题。兼容 221 比较麻烦的点，一个是降低 Java 版本，然后要降低 Kotlin 版本，要重写一些组件什么的。
