### ISSUE TITLE
Isn't calling flatten after chunked just undoing it?

### ISSUE THREAD

**Issue by jiarongfu** [unit-mesh/auto-dev#61]
https://github.com/unit-mesh/auto-dev/blob/fe52832442bc61642428245246016f8024dd7898/src/main/kotlin/com/intellij/temporary/similar/chunks/SimilarChunksWithPaths.kt#L133

Calling flatten after chunked basically just undoes chunked. I think the method 'extractChunks' is meant to split files into length 60 code snippets, but instead it returns first 60 lines of code of each file in a list. Could be an oversight here.

**Comment by phodal** [comment]
Welcome to PR.
