### ISSUE TITLE
Azure Config Custom OpenAI Host

### ISSUE THREAD

**Issue by DarrenChenGo** [unit-mesh/auto-dev#62]
Hello Phodal,

endpoint With Key In URL

https://xxx.openai.azure.com/openai/deployments/xxx/chat/completions?api-version=xxx&api-key=xxx

请问是这样配置吗？ 如果是的话，我这样配完貌似没有什么反应，不确定什么问题？有空解答一下哈，谢谢～

**Comment by DarrenChenGo** [comment]
private val autoDevSettingsState = AutoDevSettingsState.getInstance()
    private val url = autoDevSettingsState.customEngineServer

看代码 这里取的是 customEngineSever 的URL，但对于Azure来说，配置界面好像没有这个地方可以配置，是不是要取customOpenAiHost？

**Comment by phodal** [comment]
理论上应该是取这个 OpenAiHost，欢迎来 PR。

PS：@iptton 哈，是不是改出 bug 了

**Comment by hotip** [comment]
> ```
> private val autoDevSettingsState = AutoDevSettingsState.getInstance()
> private val url = autoDevSettingsState.customEngineServer
> ```
> 
> 看代码 这里取的是 customEngineSever 的URL，但对于Azure来说，配置界面好像没有这个地方可以配置，是不是要取customOpenAiHost？

这个类应该删除掉的，我看看是不是又漏了

**Comment by hotip** [comment]
> 理论上应该是取这个 OpenAiHost，欢迎来 PR。
> 
> PS：@iptton 哈，是不是改出 bug 了

这个问题 #31  你修复过的。  @phodal 

其实都是从 state 里获取了一次值后就固定了，当前不修复的话，可以直接重启 IDE 生效，要修改，需要把 url 改成 getter 函数

**Comment by phodal** [comment]
@hotip 会不会，上次重构完  dropdown  之后，选   azure 就没了那个输入框？

**Comment by phodal** [comment]
@DarrenChenGo 这里有新包，可以测试一下：https://github.com/unit-mesh/auto-dev/actions/runs/7178380264 。如果没有问题的话，我就发布到插件市场

**Comment by hotip** [comment]
> @hotip 会不会，上次重构完 dropdown 之后，选 azure 就没了那个输入框？
> 
> Azure 示例：
> 
> <img alt="图片Azure" width="725" src="https://private-user-images.githubusercontent.com/472311/289780494-77441a4c-c775-4805-910a-92ce15b40436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjgzNDAsIm5iZiI6MTcwMjM2ODA0MCwicGF0aCI6Ii80NzIzMTEvMjg5NzgwNDk0LTc3NDQxYTRjLWM3NzUtNDgwNS05MTBhLTkyY2UxNWI0MDQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwODAwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTgzYzdkYmY5ZjBmZTE4ZTM2ODRkMTQwZjkwNGUwOTNjMzQxNDRhYjZmYTUyZjc0MjdiNzNkYmQ1ZTBhOGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qPzxQ-14_z7oErCLY7ZwIiKFsET68vJTD1IZhKMhE1o">
> 自定义 Server:
> 
> ![WX20231212-153829@2x](https://private-user-images.githubusercontent.com/472311/289780533-691a5c5b-f0d1-421e-a4f7-20cd60de3a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjgzNDAsIm5iZiI6MTcwMjM2ODA0MCwicGF0aCI6Ii80NzIzMTEvMjg5NzgwNTMzLTY5MWE1YzViLWYwZDEtNDIxZS1hNGY3LTIwY2Q2MGRlM2E4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwODAwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzdmZjgwY2IyZWJkY2I3MDJlYmIxZjBmNmY4MWYzOGE1MDg0MTdmMzQwYjA3MGQ5ZDI4YzU3MGNiZDJjMWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CIYFPA3GAs2CQ1SFpEMtCUwl8gjYobDiiKi1psTEKbE)

PR 已经改成 openAiHost 了
