### ISSUE TITLE
custom配置咨询

### ISSUE THREAD

**Issue by songyb-jk** [unit-mesh/auto-dev#68]
<img width="747" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/39553855/87a17813-5dd6-4c8a-86d9-0fb8fd839518">

使用的是1.5.1-222版本的插件，AI Engine选择了Custom，请问Custom Request Body Format (Json Path) 这个选项怎么配置，我这边一直报Failed to parse custom request body的错误

**Comment by phodal** [comment]
参考一下：https://ide.unitmesh.cc/custom/llm-server#custom-request-format

**Comment by songyb-jk** [comment]
黄老师，能否像Custom response format 一样给个demo呢？

**Comment by phodal** [comment]
上面不是有？ @iptton 有空来一个像 OpenAI ?
