### ISSUE TITLE
解析response时报错

### ISSUE THREAD

**Issue by songyb-jk** [unit-mesh/auto-dev#69]
<img width="720" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/39553855/22b2cef1-1df4-44cb-a964-4e60d0b396db">

这是我的配置信息

<img width="1390" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/39553855/003638ab-23e8-44bc-b3c5-f2be1a729d95">

这个IDEA的日志，获取response之后解析报错，请问这个是什么原因，跟jdk版本有关系吗，我这边用的是1.8

**Comment by songyb-jk** [comment]
@hotip  抱歉，日志在内网，拿不出来

**Comment by phodal** [comment]
数据结构看上去没问题。不过，日志是不是不全？或者服务端异常关闭？

**Comment by songyb-jk** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/39553855/ead2963c-bd67-44d5-a24c-c40d9476d514)

这是完整的日志，服务端是正常的，用postman直接调接口都正常

**Comment by phodal** [comment]
原因应该是这个：https://stackoverflow.com/questions/58094772/okhttp-response-fail-java-lang-illegalstateexception-closed


https://github.com/unit-mesh/auto-dev/blob/5c75798eec41a1f4e99e93931f9ff88558d6558d/src/main/kotlin/cc/unitmesh/devti/llms/custom/JSONBodyResponseCallback.kt#L19-L20

>    response.body().string() → You can only call string() once.

欢迎来 PR

**Comment by songyb-jk** [comment]
#70
