### ISSUE TITLE
自定义本地模型不能正常接收sse响应

### ISSUE THREAD

**Issue by SnowWindDancing** [unit-mesh/auto-dev#73]
相同的请求，只修改response type:
如果是json可以看到有流式返回，但是插件没有打印返回；
如果是sse则可以从我们的服务看到响应体里什么都没有。

**Comment by SnowWindDancing** [comment]
改为sse后，发现自定义的属性没有一同传到服务器

**Comment by phodal** [comment]
提供的信息太少，可以看一下代码是否有问题。如果可以改 Server 的话，建议直接改为兼容 OpenAI 的格式

https://github.com/unit-mesh/auto-dev/blob/master/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt
