### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by timeisgoing** [unit-mesh/auto-dev#74]
No route to host 是什么问题呢

**Comment by phodal** [comment]
检查一下网络

**Comment by timeisgoing** [comment]
科学上网了，我这配置没问题吧 ，参考https://ide.unitmesh.cc/quick-start
<img width="732" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/24665287/4d9da6ec-cc00-4b22-be79-7f2a829edde4">

**Comment by timeisgoing** [comment]
这个Custom OpenAi Host地址需要填写吗

**Comment by phodal** [comment]
理论上现在的配置就是对的，但是网络这个项目问题解决不了

**Comment by timeisgoing** [comment]
我本身直接访问openapi是可以的；我试了idea中使用也不行。报错：  Error in stream   java.net.NoRouteToHostException: No route to host
【网络这个项目问题解决不了】 是因为我当前设备环境网络？

**Comment by phodal** [comment]
嗯，也可以看看  IDEA 是不是配置了代理之类的

**Comment by timeisgoing** [comment]
奇怪 我检查检查

**Comment by kenWu-github** [comment]
有人解决了吗？ 我这边也是connect timeout

**Comment by timeisgoing** [comment]
> 有人解决了吗？ 我这边也是connect timeout

没有啊 ，我这两天在研究自己写个插件调用openai。我再试试

**Comment by PineREN** [comment]
百度”Pycharm配置代理“解决了，设置->外观与行为->HTTP代理->手动代理配置->主机：127.0.0.1 端口号: 7890（如果是clash的话）
