### ISSUE TITLE
 com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'committer' at row 1

### ISSUE THREAD

**Issue by timeisgoing** [unit-mesh/auto-dev#75]
in context with path [] threw exception [Request processing failed; nested exception is org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: Data truncation: Data too long for column 'committer' at row 1 [statement:"
archguard-backend   |         INSERT INTO scm_change_entry (system_id,old_path,new_path,commit_time,cognitive_complexity,change_mode,commit_id,committer,line_added,line_deleted)
archguard-backend   |         VALUES (:systemId,:item.oldPath,:item.newPath,:item.commitTime,:item.cognitiveComplexity,:item.changeMode,:item.commitId,:item.committer,:item.lineAdded,:item.lineDeleted)
archguard-backend   |         ON DUPLICATE KEY UPDATE commit_id=commit_id

**Comment by phodal** [comment]
Not related to this project.
