### ISSUE TITLE
自定义模型配置支持

### ISSUE THREAD

**Issue by xiaoshyang** [unit-mesh/auto-dev#84]
我们公司内部封装了各大模型，统一暴露了一个接口，现在无法配置使用，内部使用有自己的token，还有些自定义的参数是必填的。另外看request body 和response path那的配置有些懵逼。可以举个例子。这样有个参考，更方便小白用户接入

**Comment by phodal** [comment]
示例里的就是某公司的：https://ide.unitmesh.cc/custom/llm-server#custom-request-format

再详细的话，应该也没有了。

**Comment by iptton** [comment]
> > 示例里的就是某公司的：https://ide.unitmesh.cc/custom/llm-server#custom-request-format
> > 
> > 再详细的话，应该也没有了。
> 
> 回头我再细化下这个配置说明吧，其实看代码最快，有相关的单测..

https://github.com/unit-mesh/auto-dev/blob/master/src/test/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProviderTest.kt

**Comment by phodal** [comment]
文档已更新 https://ide.unitmesh.cc/custom/llm-server#custom-request-format
