### ISSUE TITLE
增加对chatglm.cn 的支持

### ISSUE THREAD

**Issue by wizardbyron** [unit-mesh/auto-dev#90]
RT

**Comment by phodal** [comment]
2024.5.7 版本，可以支持，但是不支持  stream: true  参数

<img width="1308" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/aebc634d-c5bd-46a3-afc4-1ffb599e84e4">

**Comment by phodal** [comment]
使用  custom llm 可以支持：https://ide.unitmesh.cc/custom/llm-server

<img width="1254" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/a1d9b6e8-b325-4e31-b9d5-a1348686841c">
