### ISSUE TITLE
我使用Custom LLM Server掉用deepseek-coder模型怎么看不到相应结果呢？

### ISSUE THREAD

**Issue by liuq29** [unit-mesh/auto-dev#96]
<img width="960" alt="1212" src="https://github.com/unit-mesh/auto-dev/assets/20152198/12cd37e9-0a43-4524-a7b2-6a883b3374c0">

**Custom LLM Server配置如下：**
AI Engine：Custom
Custom Response Type：JSON
Custom Engine Server：https://api.deepseek.com/v1/chat/completions
Custom Engine Token：我的api_key
Custom Response Format（Json path）：$.choices[0].message.content
Custom Request Body Format（Json path）：{ "customFields": {"user": "liuqdsds", "model":"deepseek-coder", "stream": true},  "messageKeys": { "content": "content" }}
**我使用postman掉用deepseek-coder模型请求和响应如下：**
### request：

```json
{
    "model": "deepseek-coder",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "你好"
        }
    ]
}
```

## response：

```json
{
    "id": "fb00213d-7231-4f02-ab08-20b02dcc4c4c",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "logprobs": null,
            "message": {
                "content": "你好！有什么编程或者计算机科学相关的问题我可以帮助你解答吗？\n",
                "role": "assistant",
                "function_call": null,
                "tool_calls": null
            }
        }
    ],
    "created": 1709391303,
    "model": "deepseek-coder",
    "object": "chat.completion",
    "system_fingerprint": null,
    "usage": {
        "completion_tokens": 21,
        "prompt_tokens": 19,
        "total_tokens": 40
    }
}
```

**Comment by phodal** [comment]
SSE  接口方式是之前经过比较详细的测试，用  JSON  的比较少。

出错可以查看右下角是否有报错之类的，或者看看日志。

<img width="573" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/131a062c-fcab-4f35-8d5b-467f2eb37be8">

详细的代码见：

https://github.com/unit-mesh/auto-dev/blob/371be19433aeeed132f338a38e8680fdfbe8aef1/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt#L100-L108

**Comment by phodal** [comment]
DeepSeek 的 SSE  API  返回的结果是：

```json
{
  "id": "13505b1c-a4e9-476c-a1a3-d25962be144d",
  "choices": [
    {
      "delta": {
        "content": "\n",
        "function_call": null,
        "role": null,
        "tool_calls": null
      },
      "finish_reason": null,
      "index": 0,
      "logprobs": null
    }
  ],
  "created": 9810483,
  "model": "deepseek-chat",
  "object": "chat.completion.chunk",
  "system_fingerprint": null,
  "usage": null
}
```

对应的配置应该是：

response: `$.choices[0].delta.content `

request: 
```json
{ "customFields": {"model": "deepseek-chat", "stream": true},   "messageKeys": {"role": "role", "content": "content"} }
```

**Comment by liuq29** [comment]
好的，谢谢，我按照你说的使用SSE类型就掉用成功了，并且有返回结果了，非常感谢！

**Comment by knavet** [comment]
目前又不行了。
版本：Rider 2024.1.3
Plugin: Autodev v1.8.7-RELEASE-241

Custom Engine: `https://api.deepseek.com/chat/completions (试过 https://api.deepseek.com/v1/chat/completions 也一样）
`

Response Format: `$.choices[0].message.content` (试过 $.choices[0].delta.content 也不行）
Custom Request Format: `{ "customFields": {"model": "deepseek-chat", "stream": true},   "messageKeys": {"role": "role", "content": "content"} }`

Custom Engine Prompt: 空

用了Postman 尝试:
1. POST = https://api.deepseek.com/chat/completions
2. JSON Body:
`{
        "model": "deepseek-chat",
        "messages": [
          {"role": "system", "content": "You are a helpful assistant."},
          {"role": "user", "content": "Hello!"}
        ],
        "stream": false
      }`
3. HTTP Response:
`
{
  "id": ".......................",
  "choices": [
    {
      "index": 0,
      "message": {
        "content": "Hello! How can I assist you today?",
        "role": "assistant"
      },
      "finish_reason": "stop",
      "logprobs": null
    }
  ],
  "created": 1719046816,
  "model": "deepseek-chat",
  "system_fingerprint": ".........",
  "object": "chat.completion",
  "usage": {
    "prompt_tokens": 17,
    "completion_tokens": 9,
    "total_tokens": 26
  }
}`

**Comment by formagic** [comment]
+1,1.8.18 241版本也不行了，报错Caused by: AutoDevHttpException(statusCode=422, message=Failed to deserialize the JSON body into the target type: missing field `model` at line 1 column 45)

**Comment by phodal** [comment]
@formagic 错误不是很明显，你没填  model

**Comment by Nicolas-Gong** [comment]
> +1,1.8.18 241版本也不行了，报错Caused by: AutoDevHttpException(statusCode=422, message=Failed to deserialize the JSON body into the target type: missing field `model` at line 1 column 45)

![image](https://github.com/user-attachments/assets/72efafb6-c48b-43bb-be85-6d76059a97d8)

**Comment by phodal** [comment]
@Nicolas-Gong 参考  https://github.com/unit-mesh/auto-dev/issues/255

**Comment by Nicolas-Gong** [comment]
> @Nicolas-Gong 参考  https://github.com/unit-mesh/auto-dev/issues/255

我这么配置就可以用了…他们有兼容openai的方案

**Comment by phodal** [comment]
OpenAI 不同版本不一样，有的版本支持 functiontool，我上次试的好多不支持。

**Comment by 15866671769** [comment]
讲真我有点无语了，怎么配置最新的deepseek r1都不成功，示例图片也不一样，我的chatbox都配置成功了
