### ISSUE TITLE
SSEFormatException: Invalid sse format! ': ping 

### ISSUE THREAD

**Issue by jialiu-github** [unit-mesh/auto-dev#97]
error message: "2024-03-05 10:07:20,046 [1749283] SEVERE - #cc.unitmesh.devti.util.LLMCoroutineScope - java.io.IOException: com.theokanning.openai.service.SSEFormatException: Invalid sse format! ': ping - 2024-03-05 02:07:20.310586'
java.lang.RuntimeException: java.io.IOException: com.theokanning.openai.service.SSEFormatException: Invalid sse format! ': ping - 2024-03-05 02:07:20.310586'"

Ide version: 232

**Comment by phodal** [comment]
Notes:  SSE-Starlette support for ping event

https://github.com/sysid/sse-starlette/issues/16
